generatorName: go
outputDir: /local/v8

gitUserId: fingerprintjs
gitRepoId: go-sdk/v8

globalProperties:
  apiTests: false
  modelTests: false

additionalProperties:
  packageName: fingerprint
  disallowAdditionalPropertiesIfNotPresent: false

enablePostProcessFile: false

files:
  fingerprint_api_error.go.mustache:
    destinationFilename: api_error.go
  fingerprint_client_wrapper.go.mustache:
    destinationFilename: client_wrapper.go
  fingerprint_options.go.mustache:
    destinationFilename: options.go
  fingerprint_region.go.mustache:
    destinationFilename: region.go
  fingerprint_sealed.go.mustache:
    destinationFilename: sealed.go
  fingerprint_webhook.go.mustache:
    destinationFilename: webhook.go
  fingerprint_SealedResults.md.mustache:
    destinationFilename: docs/SealedResults.md
  fingerprint_DecryptionKey.md.mustache:
    destinationFilename: docs/DecryptionKey.md
  fingerprint_Webhook.md.mustache:
    destinationFilename: docs/Webhook.md
